CREATE TABLE UTILISATEUR
(
    ID_UTILISATEUR INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOM_UTILISATEUR VARCHAR(50) NOT NULL,
    PRENOM_UTILISATEUR VARCHAR(50) NOT NULL,
    EMAIL_UTILISATEUR VARCHAR(50) NOT NULL,
    MDP_UTILISATEUR VARCHAR(50) NOT NULL,
    ADRESSE_UTILISATEUR VARCHAR(50) NOT NULL,
    TELEPHONE_UTILISATEUR VARCHAR(20) NOT NULL,
    DATE_NAISSANCE_UTILISATEUR DATE NOT NULL
);
