CREATE TABLE MAPPING_PANIER_GRAINE
(
    ID_PANIER INT NOT NULL,
    ID_GRAINE INT NOT NULL,
    QUANTITE INT NOT NULL,
    PRIX DECIMAL(7,2) NOT NULL,
    FOREIGN KEY (ID_PANIER) REFERENCES PANIER(ID_PANIER),
    FOREIGN KEY (ID_GRAINE) REFERENCES GRAINE(ID_GRAINE),
    PRIMARY KEY (ID_PANIER,ID_GRAINE)
);