CREATE TABLE MAPPING_PROMOTION_GRAINE
(
    ID_PROMOTION INT NOT NULL,
    ID_GRAINE INT NOT NULL,
    FOREIGN KEY (ID_PROMOTION) REFERENCES PROMOTION(ID_PROMOTION),
    FOREIGN KEY (ID_GRAINE) REFERENCES GRAINE(ID_GRAINE),
    PRIMARY KEY (ID_PROMOTION,ID_GRAINE)
);