CREATE TABLE PROMOTION
(
    ID_PROMOTION INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOM_PROMOTION VARCHAR(100) NOT NULL
    DATE_DEBUT_PROMOTION DATETIME NOT NULL,
    DATE_FIN_PROMOTION DATETIME NOT NULL, 
);