CREATE TABLE PANIER
( 
  ID_PANIER INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  PRIX_PANIER DECIMAL(7,2) NOT NULL,
  ID_VISITEUR INT,
  ID_UTILISATEUR INT,
  FOREIGN KEY (ID_VISITEUR) REFERENCES VISITEUR(ID_VISITEUR),
  FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
);
