SELECT R.ID_RECETTE
FROM RECETTE R
INNER JOIN JARDINIER J ON R.ID_JARDINIER = J.ID_JARDINIER
INNER JOIN MAPPING_RECETTE_GRAINE RG ON R.ID_RECETTE = RG.ID_RECETTE
LEFT OUTER JOIN MAPPING_PANIER_GRAINE PG ON RG.ID_GRAINE = PG.ID_GRAINE
INNER JOIN ACHAT A ON PG.ID_PANIER = A.ID_PANIER
GROUP BY R.ID_RECETTE
HAVING COUNT(*) = COUNT(PG.ID_GRAINE);